### ISSUE TITLE
Dihedral angle for the oxygen in the carbonyl group

### ISSUE THREAD

**Issue by hypnopump** [jonathanking/sidechainnet#14]
I have noticed that you pass the dihedral angle for the oxygen in the carbonyl group as `psi - np.pi` and vector that you use in the `nerf` function to place the oxygen has it's first entry equals to `-l * cos(theta)`. I wonder if this notation is correct or if it could be simplified by passing the `psi` angle without correction and modifiyng the vector's first entry to `l * cos(theta)`. 

From my own tests, the vector's first entry shouldn't have the negative sign (tested with custom examples of 4 points), so i wonder if the `psi - np.pi` has something to do with protein structure or it's a correction to the negative sign in the `nerf` function.

**Comment by jonathanking** [comment]
Thank you very much for pointing this out. I'll take a closer look.

**Comment by jonathanking** [comment]
I think there might be two issues to discuss here, 1) using `psi - np.pi` to place the carbonyl oxygen, and 2) using a negative sign in the first entry of the rotation matrix within the `nerf` function.

1. I have chosen to assume that the dihedral angle that describes the placement of the carbonyl oxygen is equal to pi minus the value of the psi angle for the same residue. Because the alpha-carbon, carbonyl-carbon, carbonyl-oxygen, and nitrogen of the next residue are all in the same plane, I believe this is a realistic conclusion. In all of my work, it has correctly placed the carbonyl-oxygens. 
2. Can you share your tests? I'm trying to figure this out for myself. I do realize that in the original papers there is no negative sign, but way back when I first started working on this problem I used the nerf function found [here](https://github.com/rbhatta8/protein-design/blob/master/nerf.py), which includes the negative sign. In all of my structure generation tasks, this function works as expected. 

I'd like to figure out #2 for my own clarity, but I hope I have still been able to satisfy your concern. I do not think the two issues are related, and I think I have made a good case for using `psi-np.pi` to place the carbonyl-oxygens. In any case, I'd love to hear your thoughts on the matter.

**Comment by hypnopump** [comment]
here you are! You'll see that by leaving the `-` sign out, it will make the reconstruction fine!

```python3
import torch
import numpy as np

def nerf(a, b, c, l, theta, chi):
    """
    Natural extension reference frame method for placing the 4th atom given
    atoms 1-3 and the relevant angle inforamation. This code was originally
    written by Rohit Bhattacharya (rohit.bhattachar@gmail.com,
    https://github.com/rbhatta8/protein-design/blob/master/nerf.py) and I
    have extended it to work with PyTorch. His original documentation is
    below:
    Nerf method of finding 4th coord (d) in cartesian space
        Params:
            a, b, c : coords of 3 points
            l : bond length between c and d
            theta : bond angle between b, c, d (in degrees)
            chi : dihedral using a, b, c, d (in degrees)
        Returns:
            d: tuple of (x, y, z) in cartesian space
    """
    # calculate unit vectors AB and BC
    if not (-np.pi <= theta <= np.pi):
        raise ValueError(f"theta must be in radians and in [-pi, pi]. theta = {theta}")

    W_hat = torch.nn.functional.normalize(b - a, dim=0)
    x_hat = torch.nn.functional.normalize(c - b, dim=0)

    # calculate unit normals n = AB x BC
    # and p = n x BC
    n_unit = torch.cross(W_hat, x_hat)
    z_hat = torch.nn.functional.normalize(n_unit, dim=0)
    y_hat = torch.cross(z_hat, x_hat)

    # create rotation matrix [BC; p; n] (3x3)
    M = torch.stack([x_hat, y_hat, z_hat], dim=1)

    # calculate coord pre rotation matrix
    d = torch.stack([
        torch.squeeze(-l * torch.cos(theta)),
        torch.squeeze(l * torch.sin(theta) * torch.cos(chi)),
        torch.squeeze(l * torch.sin(theta) * torch.sin(chi))
    ])
    # calculate with rotation as our final output
    # TODO: is the squeezing necessary?
    d = d.unsqueeze(1).to(torch.float32)
    res = c + torch.mm(M, d).squeeze()
    return res.squeeze()


# gen points
a = torch.tensor([1,2,3]).float()
b = torch.tensor([1,4,5]).float()
c = torch.tensor([1,4,7]).float()
d = torch.tensor([1,8,2]).float()


# get measures
v1 = (b-a).numpy()
v2 = (c-b).numpy()
v3 = (d-c).numpy()
# get angles
theta = np.arccos( np.dot(v2, v3) / \
                  (np.linalg.norm(v2) * np.linalg.norm(v3) )) 

normal_p  = np.cross(v1, v2) 
normal_p_ = np.cross(v2, v3)
chi = np.arccos( np.dot(normal_p, normal_p_) / \
                (np.linalg.norm(normal_p) * np.linalg.norm(normal_p_) ))
# get length:
l = np.linalg.norm(v3)


print("theta, chi, l", theta, chi, l)
d_ = nerf(a, b, c, torch.tensor(l), torch.tensor(theta), torch.tensor(chi))
print("target: {0}, reconstructed: {1}".format(d, d_))
```

**Comment by jonathanking** [comment]
Hmm, yeah, you're right that it works in this case. Thanks for sharing this example. However, it's still necessary in SidechainNet. I think it might be related to the way that I've recorded the 3-atom bond angles with ProDy. If you remove the negative sign in SidechainNet, the structure generation certainly doesn't work.

There are several other NeRF code examples written by others that also rely on the negative sign, so I'm not sure why. Even in AlQuraishi's RGN code the angle is inverted with a `-np.pi` before going into the cosine. If you have any thoughts on why, that would be really interesting to hear. I'm still looking into this as well. 

Also, again, I think the two issues you brought up are unrelated. Does that sound right to you?

**Comment by hypnopump** [comment]
Yes, after taking a closer look, they seem separate issues. For the rest, i think it all might be about the references one take, thus it may be convenient in some cases to add a `-π` to some angles.
